# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: MkDocs Material Demo
site_url: https://bergmann-max.github.io/MkDocs-Material-Demo/
repo_url: https://github.com/bergmann-max/MkDocs-Material-Demo
repo_name: bergmann-max/MkDocs-Material-Demo
edit_uri: blob/master/docs/
site_dir: public
# leave 'nav' unset for automatic navigation
theme:
    name: material
    custom_dir: overrides
    language: en
    logo: assets/logo.png
    favicon: assets/favicon.ico
    icon:
        admonition:
            note: fontawesome/solid/note-sticky
            abstract: fontawesome/solid/book
            info: fontawesome/solid/circle-info
            tip: fontawesome/solid/bullhorn
            success: fontawesome/solid/check
            question: fontawesome/solid/circle-question
            warning: fontawesome/solid/triangle-exclamation
            failure: fontawesome/solid/bomb
            danger: fontawesome/solid/skull
            bug: fontawesome/solid/robot
            example: fontawesome/solid/flask
            quote: fontawesome/solid/quote-left
        repo: fontawesome/brands/github
        edit: material/pencil
        tag:
            formatting: material/format-text
            content: material/card-text
            media: material/image
            code: material/code-tags
    features:
        - content.action.edit
        - content.code.copy
        - content.tabs.link
        - content.tooltips
        - search.suggest
        - search.highlight
        - search.share
        - header.autohide
        - announce.dismiss
        - navigation.instant
        - navigation.instant.progress
        - navigation.tracking
        - navigation.path
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.top
        - navigation.indexes
        - navigation.sections
        - toc.integrate
        - toc.follow
    # When sections are enabled, top-level sections are rendered as groups in the sidebar for viewports above 1220px, but remain as-is on mobile.
    #       - navigation.sections
    # When expansion is enabled, the left sidebar will expand all collapsible subsections by default, so the user doesn't have to open subsections manually.
    #       - navigation.expand
    palette:
        # Palette toggle for light mode
        - scheme: default
          media: "(prefers-color-scheme: light)"
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode
        # Palette toggle for dark mode
        - scheme: slate
          media: "(prefers-color-scheme: dark)"
          toggle:
              icon: material/brightness-4
              name: Switch to light mode
plugins:
    - privacy
    - social
    - tags:
          tags_hierarchy: true
    - search:
          lang: en
          separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
    - glightbox:
          touchNavigation: true
          loop: true
          effect: zoom
          slide_effect: slide
          width: 100%
          height: auto
          zoomable: true
          draggable: true
          skip_classes:
              - custom-skip-class-name
          auto_caption: true
          caption_position: bottom
    - git-revision-date-localized:
          enable_creation_date: true
          type: date
          fallback_to_build_date: true
    - table-reader
    - blog:
          blog_dir: blog
markdown_extensions:
    - pymdownx.snippets:
          auto_append:
              - includes/abbreviations.md
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - admonition
    - pymdownx.details
    - tables
    - attr_list
    - md_in_html
    - toc:
          permalink: true
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - def_list
    - pymdownx.tasklist:
          custom_checkbox: true
    - abbr
    - footnotes
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.arithmatex:
          generic: true
extra:
    tags:
        Formatting: formatting
        Content: content
        Media: media
        Code: code
    version:
        provider: mike
        default: stable
extra_javascript:
    - javascripts/tablesort.min.js
    - javascripts/tablesort.js
    - javascripts/katex.js
    - https://unpkg.com/katex@0/dist/katex.min.js
    - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
extra_css:
    - https://unpkg.com/katex@0/dist/katex.min.css
